version: "3"
services:
  api:
    container_name: evp_api
    build: ./api
    command: gunicorn -w 4 -k uvicorn.workers.UvicornWorker api.app:app --reload --bind 0.0.0.0:80
    volumes:
      - ./api:/api
      - ./tmp:/tmp
    # image: inoue0124/eval-speech_api
    ports:
      - 8080:80
    environment:
      SECRET_KEY: "09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7"
      ALGORITHM: "HS256"
      ACCESS_TOKEN_EXPIRE_DAYS: 7
      MYSQL_USER: evalspeech
      MYSQL_PASSWORD: evalspeech
      MYSQL_HOST: evp_db
      MYSQL_DATABASE: eval-speech
      AWS_ACCESS_KEY: ${AWS_ACCESS_KEY}
      AWS_SECRET_KEY: ${AWS_SECRET_KEY}
      AWS_REGION: ${AWS_REGION}

  db:
    container_name: evp_db
    image: mysql:5.7
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - ./.data/mysql:/var/lib/mysql
      - "./ddl:/docker-entrypoint-initdb.d"
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: evalspeech
      MYSQL_PASSWORD: evalspeech
      MYSQL_DATABASE: eval-speech
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
