version: "3"
services:
  api:
    container_name: evp_api
    build: ./api
    command: uvicorn api.main:app --reload --host 0.0.0.0 --port 80
    volumes:
      - ./api:/api
    ports:
      - 8080:80
