version: "3"
services:
  api:
    container_name: evp_api
    build: ./api
    command: uvicorn api.app:app --reload --host 0.0.0.0 --port 80
    volumes:
      - ./api:/api
    # image: inoue0124/eval-speech_api
    ports:
      - 8080:80
  
  db:
    container_name: evp_db
    image: mysql:5.7
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - ./.data/mysql:/var/lib/mysql
      - "./ddl:/docker-entrypoint-initdb.d"
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: evalspeech
      MYSQL_PASSWORD: evalspeech
      MYSQL_DATABASE: eval-speech
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
